-- Disable foreign key constraints temporarily
SET session_replication_role = 'replica';

-- Reset all tables
TRUNCATE TABLE transactions CASCADE;
TRUNCATE TABLE bank_transactions CASCADE;
TRUNCATE TABLE cash_transactions CASCADE;
TRUNCATE TABLE ledger_entries CASCADE;
TRUNCATE TABLE ledgers CASCADE;
TRUNCATE TABLE payments CASCADE;
TRUNCATE TABLE expenses CASCADE;
TRUNCATE TABLE gate_entries CASCADE;
TRUNCATE TABLE gate_entries_pricing CASCADE;
TRUNCATE TABLE gate_returns CASCADE;
TRUNCATE TABLE store_entries CASCADE;
TRUNCATE TABLE store_returns CASCADE;
TRUNCATE TABLE stock_adjustments CASCADE;
TRUNCATE TABLE production CASCADE;
TRUNCATE TABLE production_paper_types CASCADE;
TRUNCATE TABLE production_recipe CASCADE;
TRUNCATE TABLE production_reels CASCADE;
TRUNCATE TABLE daily_attendance CASCADE;
TRUNCATE TABLE leave_applications CASCADE;
TRUNCATE TABLE loan_applications CASCADE;
TRUNCATE TABLE loan_installments CASCADE;
TRUNCATE TABLE salary_payments CASCADE;
TRUNCATE TABLE salary_increments CASCADE;
TRUNCATE TABLE contractor_payments CASCADE;
TRUNCATE TABLE contractor_salary_history CASCADE;
TRUNCATE TABLE monthly_salary_totals CASCADE;
TRUNCATE TABLE workers_salary_totals CASCADE;
TRUNCATE TABLE maintenance_issues CASCADE;
TRUNCATE TABLE maintenance_issue_items CASCADE;
TRUNCATE TABLE income_statement_adjustments CASCADE;
TRUNCATE TABLE monthly_price_averages CASCADE;
TRUNCATE TABLE accounts CASCADE;
TRUNCATE TABLE bank_accounts CASCADE;
TRUNCATE TABLE cash_tracking CASCADE;
TRUNCATE TABLE chart_of_accounts CASCADE;
TRUNCATE TABLE chart_of_accounts_level1 CASCADE;
TRUNCATE TABLE chart_of_accounts_level2 CASCADE;
TRUNCATE TABLE chart_of_accounts_level3 CASCADE;
TRUNCATE TABLE contractors CASCADE;
TRUNCATE TABLE departments CASCADE;
TRUNCATE TABLE employees CASCADE;
TRUNCATE TABLE expense_types CASCADE;
TRUNCATE TABLE final_settlements CASCADE;
TRUNCATE TABLE item_types CASCADE;
TRUNCATE TABLE paper_types CASCADE;
TRUNCATE TABLE purchasers CASCADE;
TRUNCATE TABLE store_items CASCADE;
TRUNCATE TABLE suppliers CASCADE;

-- Reset all sequences
ALTER SEQUENCE transactions_id_seq RESTART WITH 1;
ALTER SEQUENCE bank_transactions_id_seq RESTART WITH 1;
ALTER SEQUENCE cash_transactions_id_seq RESTART WITH 1;
ALTER SEQUENCE ledger_entries_id_seq RESTART WITH 1;
ALTER SEQUENCE ledgers_id_seq RESTART WITH 1;
ALTER SEQUENCE payments_id_seq RESTART WITH 1;
ALTER SEQUENCE expenses_id_seq RESTART WITH 1;
ALTER SEQUENCE gate_entries_id_seq RESTART WITH 1;
ALTER SEQUENCE gate_entries_pricing_id_seq RESTART WITH 1;
ALTER SEQUENCE gate_returns_id_seq RESTART WITH 1;
ALTER SEQUENCE store_entries_id_seq RESTART WITH 1;
ALTER SEQUENCE store_returns_id_seq RESTART WITH 1;
ALTER SEQUENCE stock_adjustments_id_seq RESTART WITH 1;
ALTER SEQUENCE production_id_seq RESTART WITH 1;
ALTER SEQUENCE production_paper_types_id_seq RESTART WITH 1;
ALTER SEQUENCE production_recipe_id_seq RESTART WITH 1;
ALTER SEQUENCE production_reels_id_seq RESTART WITH 1;
ALTER SEQUENCE daily_attendance_id_seq RESTART WITH 1;
ALTER SEQUENCE leave_applications_id_seq RESTART WITH 1;
ALTER SEQUENCE loan_applications_id_seq RESTART WITH 1;
ALTER SEQUENCE loan_installments_id_seq RESTART WITH 1;
ALTER SEQUENCE salary_payments_id_seq RESTART WITH 1;
ALTER SEQUENCE salary_increments_id_seq RESTART WITH 1;
ALTER SEQUENCE contractor_payments_id_seq RESTART WITH 1;
ALTER SEQUENCE contractor_salary_history_id_seq RESTART WITH 1;
ALTER SEQUENCE monthly_salary_totals_id_seq RESTART WITH 1;
ALTER SEQUENCE workers_salary_totals_id_seq RESTART WITH 1;
ALTER SEQUENCE maintenance_issues_id_seq RESTART WITH 1;
ALTER SEQUENCE maintenance_issue_items_id_seq RESTART WITH 1;
ALTER SEQUENCE income_statement_adjustments_id_seq RESTART WITH 1;
ALTER SEQUENCE monthly_price_averages_id_seq RESTART WITH 1;
ALTER SEQUENCE accounts_id_seq RESTART WITH 1;
ALTER SEQUENCE bank_accounts_id_seq RESTART WITH 1;
ALTER SEQUENCE cash_tracking_id_seq RESTART WITH 1;
ALTER SEQUENCE chart_of_accounts_id_seq RESTART WITH 1;
ALTER SEQUENCE chart_of_accounts_level1_id_seq RESTART WITH 1;
ALTER SEQUENCE chart_of_accounts_level2_id_seq RESTART WITH 1;
ALTER SEQUENCE chart_of_accounts_level3_id_seq RESTART WITH 1;
ALTER SEQUENCE contractors_id_seq RESTART WITH 1;
ALTER SEQUENCE departments_id_seq RESTART WITH 1;
ALTER SEQUENCE expense_types_id_seq RESTART WITH 1;
ALTER SEQUENCE final_settlements_id_seq RESTART WITH 1;
ALTER SEQUENCE item_types_id_seq RESTART WITH 1;
ALTER SEQUENCE paper_types_id_seq RESTART WITH 1;
ALTER SEQUENCE purchasers_id_seq RESTART WITH 1;
ALTER SEQUENCE store_items_id_seq RESTART WITH 1;
ALTER SEQUENCE suppliers_id_seq RESTART WITH 1;

-- Re-enable foreign key constraints
SET session_replication_role = 'origin'; 